name: Build PDF on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build_pdf.yml
    secrets: inherit
    with:
      tag: ${{ github.event.release.tag_name }}

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Retrieve PDF
        uses: actions/download-artifact@v4
        with:
          name: releasepdf
          path: ${{ needs.build.outputs.pdfname }}

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build.outputs.pdfname }}

      - name: Add to step summary
        if: ${{ success() }}
        env:
          PDF_NAME: ${{ needs.build.outputs.pdfname }}
        run: echo "## Successfully built $PDF_NAME" >> $GITHUB_STEP_SUMMARY
