name: Build PDF on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get repo and tag names
        id: vars
        env:
          REPO_NAME: $(basename $GITHUB_REPOSITORY)
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          output_name="${REPO_NAME}_version_${TAG_NAME}.pdf"
          echo "output_name=$output_name" >> $GITHUB_OUTPUT

      - name: Compile PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Rename PDF
        run: mv main.pdf ${{ steps.vars.outputs.output_name }}

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.vars.outputs.output_name }}

      - name: Add to step summary
        if: ${{ success() }}
        env:
          PDF_NAME: ${{ steps.vars.outputs.output_name }}
        run: echo "## Successfully built $PDF_NAME" >> $GITHUB_STEP_SUMMARY
