name: Create Release from PR

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  create-tag:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    outputs:
      tag_name: ${{ steps.tag.outputs.date_tag }}
    steps:
      - name: Set tag name
        id: tag
        run: echo "date_tag=$(date +%F)" >> $GITHUB_OUTPUT

  build:
    needs: create-tag
    if: ${{ needs.create-tag.result == 'success' }}
    uses: ./.github/workflows/build_pdf.yml
    secrets: inherit
    with:
      tag: ${{ needs.create-tag.outputs.tag_name }}

  create-release:
    runs-on: ubuntu-latest
    needs: [create-tag, build]
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Check out PR
        uses: actions/checkout@v4

      - name: Retrieve PDF
        uses: actions/download-artifact@v4
        with:
          name: releasepdf
          path: ./artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create-tag.outputs.tag_name }}
          name: Version ${{ needs.create-tag.outputs.tag_name }}
          artifacts: artifacts/${{ needs.build.outputs.pdfname }}
          generateReleaseNotes: true
